name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main
      - "**" # This will trigger on any branch push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use the Node.js version your project requires

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          publish_branch: gh-pages
          destination_dir: ${{ github.ref_name != 'main' && github.ref_name || '.' }} # Deploy to root on main, to folder for other branches
          user_name: olgagr # Customize with your GitHub username
          user_email: olga.grabek@gmail.com

      - name: Link Storybook
        run: |
          URL="https://olgagr.github.io/storybook_experiment"
          if [ "${{ github.ref }}" != "refs/heads/main" ]; then
            URL="$URL/${{ github.ref_name }}"
          fi
          curl -X "POST" "https://c463-212-59-69-218.ngrok-free.app/open_api/v1/styleguides/2/storybooks_settings" \
          -H 'X-API-CLIENT: ${{secrets.X_API_CLIENT}}' \
          -H 'X-API-KEY: ${{secrets.X_API_KEY}}' \
          -H 'Content-Type: application/json; charset=utf-8' \
          -d "{
            \"title\": \"branch\",
            \"main_storybook_url\": \"https://olgagr.github.io/storybook_experiment\",
            \"storybook_url\": \"$URL\"
          }"
